
apiVersion: apps/v1
kind: Deployment
metadata:
 name: deployment1
spec:
 strategy:
   type: RollingUpdate
 replicas: 2
 selector:
   matchLabels:
     app: nginx
 template:
   metadata:
    name: myPod
    labels:
      app: nginx
   spec:
    containers:
    - name: mycontainer
      imagePullPolicy: Always
      image: sarikawalake04/prt-demo:v1
      ports:
        - containerPort: 80
